### PR TITLE
Hours converter

### PR DESCRIPTION
**Pull request by ali1996-sy**

### CODE REVIEW

**Review by harunaltunhr — CHANGES_REQUESTED** [review]
You do not need to change anything from index.html

**Comment by ali1996-sy** [comment]
you have reason, sorry it was for testing

**Review by harunaltunhr — CHANGES_REQUESTED** [review]
Still wrong my friend... You did not change index.html. We could not see index.html in here

**Comment by harunaltunhr** [comment]
> Still wrong my friend... You did not change index.html. We could not see index.html in here

In your local repo, please change only YOUR PART not index.html. You sent index.html too. And when merging it will be conflict

**Review by harunaltunhr — CHANGES_REQUESTED** [review]
And convert-minutes.js should not be in this branch

**Pull request closed without merging**
