### PR TITLE
hours-converter closed #11

### LINKED ISSUE #11: Converting to hours
- [x]  The new repo branch seconds was generated.

- [x]   The core logic function was developed.
- [x]   An appropriate handler was developed to use the function interactively.
- [x]   PR was raised, reviewed by two assigned reviewers and the branch was merged to the master branch.

### PR DESCRIPTION
**Pull request by ali1996-sy**

### CODE REVIEW

**Review by harunaltunhr — CHANGES_REQUESTED** [review]
Please Look our codes :)) Do not Hurry, no rush. We are try to build SIMILAR ALERT...

**Comment by harunaltunhr** [comment]
> Please Look our codes :)) Do not Hurry, no rush. We are try to build SIMILAR ALERT...

https://github.com/LujiAnna/testing-module-Week-Converter/pull/14/files
From this code, weeks is always Number, so no need to check it again. And maybe User wants to see 0 weeks how long Hours, I think we convert. What do you think @LujiAnna @julia-sod ?

**Review by LujiAnna — COMMENTED** [review]
Looks fine. 
But, there is another function which task it to get the number of week(s)

**Comment by LujiAnna** [comment]
> > Please Look our codes :)) Do not Hurry, no rush. We are try to build SIMILAR ALERT...
> 
> https://github.com/LujiAnna/testing-module-Week-Converter/pull/14/files
> From this code, weeks is always Number, so no need to check it again. And maybe User wants to see 0 weeks how long Hours, I think we convert. What do you think @LujiAnna @julia-sod ?

I agree. Also for a negative number

**Pull request closed without merging**
